### ISSUE TITLE
[ENHANCEMENT] base volume setting

### ISSUE THREAD

**Issue by OnefITA** [LamaDiLuce/polaris-opencore#62]
will be great (with some gesture or via pc software) to add the possibility to increase or decrease the volume.-

also at "step" let's say
MUTE - 30% - 60% - 90% - FULL
(1tap - 2tap - 3tap - 4tap - 5tap)

feel free to disregard if not applicable

**Comment by FarFlyer** [comment]
It's a nice to have feature.

We already have the TAP recognition, so it's not so complicated to implement.

We need to modify the state machine of the audio module. Now after the first TAP it enters the mute state and exits only on disarm.

This can be done from the [Automaton template editor.](http://wolkendek.nl/atm/)

I can give advices to who wants to try.

**Comment by jramboz** [comment]
My C++ is rusty, but after looking through the repo I think I could give this a try. I'd be very grateful for any tips and suggestions!

**Comment by FarFlyer** [comment]
Hello,
Feel free to ask if you need help.

You can create a branch and share the link.

Best regards,

Davide Tagliafierro
Mechatronics Engineer
Mobile: +39 329 067 0099

[from mobile]

Il Sab 5 Nov 2022, 18:19 Jason Ramboz ***@***.***> ha scritto:

**Comment by jramboz** [comment]
So far, I can see where the calls to enter the MUTE state are, but I can't figure out how it's actually muting the audio. I see `CoreAudio::action(ENT_MUTE)`, but it seems to just beep twice. How is it actually affecting the sound playback?

Also, the Automaton Template Editor appears to be offline. Do you know if there's a mirror anywhere?

**Comment by FarFlyer** [comment]
Unfortunately, the template was hosted by the creator on his own server,
but now he is in another country and cannot host it. There are no other
mirror.
The trick to enter the mute rely on the state machine and the state
transitions. With the template editor would have been more easy to
understand. You should look to the table on top of the cpp file.
Basically, entering the mute state prevents the transitions to other states.
The states transitions are also reported in this picture:
https://github.com/LamaDiLuce/polaris-opencore/wiki/Automaton#state-machine-flowcharts

Davide Tagliafierro
Mechatronics Engineer
www.daveamps.it
Mobile: +39 329 067 0099

[from mobile]

Il Sab 5 Nov 2022, 22:21 Jason Ramboz ***@***.***> ha scritto:

**Comment by jramboz** [comment]
I found the source for the template editor on his GitHub page. I'll host a local copy and continue exploring!

**Comment by FarFlyer** [comment]
Great!
I don't know where to start for hosting it XD

Davide Tagliafierro
Mechatronics Engineer
www.daveamps.it
Mobile: +39 329 067 0099

[from mobile]

Il Sab 5 Nov 2022, 23:34 Jason Ramboz ***@***.***> ha scritto:
