### ISSUE TITLE
[ENHANCEMENT] Dynamic smooth swing

### ISSUE THREAD

**Issue by f4iey** [LamaDiLuce/polaris-opencore#73]
By listening with more attention, I noticed that swing sounds felt always the same: 8 static sounds randomly selected when the accelerometer threshold is reached.

To make swing more *realistic*, I suggest having sound variations (e.g mapping audio playing speed or stretch) depending on the acceleration value.

I tought about making the swing sound loop like the hum and adjust the playing speed according to a defined mapping on the accelerometer. It maybe has to run through an interrupt vector `ISR(TIMER2_OVF_vect)` to have no delay.

I know it has been done on the proprietary *Crystal Focus X* board (which is just an ATSAMD51J19A on a PCB), a 32bit ARM Cortex M4 microcontroller.
So it should not be impossible to implement^^

**Comment by f4iey** [comment]
I just saw the smoothing feature, I'm going to have a look at it :)

**Comment by FarFlyer** [comment]
Hello @f4iey we implemented the smoothswing based on https://therebelarmory.com/thread/9138/smoothswing-v2-algorithm-description
It's basically hum sounds at different pitches blended according to the speed.
With this approach, you can use basically any sound font.
Adjusting the playing speed based on the speed/acceleration requires much computation and it's not easy to implement. One other possibility is to generate the sound dynamically based on maths, but then you lose the possibility to customize.
